spring:
   datasource:
      url: jdbc:mysql://127.0.0.1:3306/springjpa-project
      username: root
   driver-class-name: com.mysql.jdbc.Driver
   jpa:
      open-in-view: false
      show-sql: true
      hibernate:
         ddl-auto: update
   #security:
    #  user:
     #    name: MDF
      #   password: 12345
URLS:
   Authenticated: /api/student/byEmail,/api/student/update,/api/student/all,/api/course/**
   Permitall: /api/student/register